name: aps-tci
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pyarrow>=16.1.0
    - jsonpickle>=3.2.2
    - causal_testing_framework==8.1.0
    - pyswarms==1.3.0
    - python-dotenv==1.0.0
    - markovify==0.9.4
    - jinja2==3.1.4
